[package]
name = "net_loopback"
version = "0.1.0"
edition = "2024"

[dependencies]
crc = "3.3.0"
postcard = { version = "1.1.3", features = ["use-std", "use-crc"] }
serde = { version = "1.0.219", features = ["derive"] }
